---@class nitpick.FileLinterConfig
---@field meta table
---@field meta.url string
---@field meta.description string
---@field command string|fun():string
---@field stdin boolean
---@field args string[]
---@field cwd string|fun():string
